### ISSUE TITLE
Dynamic key error when using mouse button trigger

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#681]
# How OptiKey was being used
- using 3b57a33 from PR #680
- Set input source = mouse, key selection source = mouse left button. 
- Go to dynamic keyboards
- Open one of the bundled keyboards
- click on any key
- the key fails and you get an error toast: 
"An error has occurred during the handling of a key selection"

Log:
``` 
2020-06-03 10:31:44,925 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: SelectionResult event received from InputService.
2020-06-03 10:32:06,050 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Starting CommandKey key: R12-C6
2020-06-03 10:32:10,277 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: CommandKey called with singleKeyValue: R12-C6
2020-06-03 10:32:21,328 [ 1] ERROR JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Exception caught by inputServiceSelectionResultHandler
System.NullReferenceException: Object reference not set to an instance of an object.
   at JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.<CommandKey>d__78.MoveNext() in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\ViewModels\MainViewModel.ServiceEventHandlers.cs:line 2425
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.<<SetupInputServiceEventHandlers>b__63_4>d.MoveNext() in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\ViewModels\MainViewModel.ServiceEventHandlers.cs:line 141
2020-06-03 10:32:24,935 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Selection event received from InputService.
```

Issue is a null ptr `inputService.OverrideTimesByKey`

**Comment by AdamRoden** [comment]
This hit me when working on a new feature. Is there progress toward the fx, or should I take it up?

**Comment by AdamRoden** [comment]
I submit PR #734 to resolve the issue.
