### ISSUE TITLE
Combination of settings results in Optikey being unable to start

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#693]
# How OptiKey was being used

Fresh install, changed some settings, restarted = crash every time it starts

# What the user expected to happen

Normal start up

# What the user actually experienced

Crashes

# Details

Log of a crash attached, which shows the settings being used and the cause of the error:
```

2020-07-18 09:35:44,330 [ 1] ERROR JuliusSweetland.OptiKey.OptiKeyApp: Error starting up application
**System.NotImplementedException: The method or operation is not implemented.**
   at **JuliusSweetland.OptiKey.Observables.TriggerSources.KeyboardKeyDownUpSource.get_OverrideTimesByKey()** in C:\Users\Julius\Documents\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\Observables\TriggerSources\**KeyboardKeyDownUpSource.cs:line 113**
   at JuliusSweetland.OptiKey.Services.InputService.get_OverrideTimesByKey() in C:\Users\Julius\Documents\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\Services\InputService.cs:line 72
   at JuliusSweetland.OptiKey.UI.Windows.MainWindow.get_OverrideTimesByKey() in C:\Users\Julius\Documents\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\Windows\MainWindow.xaml.cs:line 108
   at JuliusSweetland.OptiKey.UI.Controls.KeyboardHost.GenerateContent() in C:\Users\Julius\Documents\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\Controls\KeyboardHost.cs:line 184
   at JuliusSweetland.OptiKey.UI.Controls.KeyboardHost.<>c.<.cctor>b__29_0(DependencyObject o, DependencyPropertyChangedEventArgs args) in C:\Users\Julius\Documents\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\Controls\KeyboardHost.cs:line 108
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at JuliusSweetland.OptiKey.Pro.App.App_OnStartup(Object sender, StartupEventArgs e) in C:\Users\Julius\Documents\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Pro\App.xaml.cs:line 183
```

# Settings being used:

PointSelectionTriggerMouseDownUpButton:   Left
--
LookToScrollBaseSpeedFast: 0
LookToScrollOverlayDeadzoneThickness: 1
PointSelectionTriggerKeyboardKeyDownUpKey:   Insert
LookToScrollBaseSpeedSlow: 0
LookToScrollIncrement: 1
PresageDatabaseLocation:
EnablePlugins: False
DynamicKeyboardsLocation:   C:\Users\matth\AppData\Roaming\OptiKey\OptiKey\Keyboards\
MouseKeyboardDockSize: Collapsed
ToastNotificationVerticalFillPercentage:   75
SimplifiedKeyboardContext: Home
KeySelectionSoundVolume: 0
ProgressIndicatorResizeStartProportion:   100
UseAlphabeticalKeyboardLayout: False
MultiKeySelectionLockedDownWhenNotSimulatingKeyStrokes:   False
MagnifierCenterOnScreen: False
NGramAutoCompleteLeadingSpaceCount: 2
AllowMultipleInstances: False
KalmanFilterProcessNoise: 5
Theme:   /Resources/Themes/Android_Dark.xaml
PointTtl: 00:00:00.1500000
MaryTTSEnabled: False
CommuniKateKeyboardPrevious1Context:
EnableCopyAllScratchpadKey: False
UiLanguage: EnglishUK
PointSelectionTriggerSource: Fixations
PointSelectionTriggerLockOnRadiusInPixels:   40
SpeechRate: 0
SpeechVolume: 100
KeySelectionTriggerFixationResumeRequiresLockOn:   False
CommuniKateSoundVolume: 50
MagnifySourcePercentageOfScreen: 10
EnableCommuniKateKeyboardLayout: False
AutoCapitalise: True
MouseMoveAmountInPixels: 25
MaryTTSLocation:
PointsMousePositionSampleInterval:   00:00:00.0130000
MouseScrollSoundFile:   Resources\Sounds\MouseScroll1.wav
MultiKeySelectionCaptureStartSoundVolume:   0
AttentionSoundFile:   Resources\Sounds\Attention.wav
MagnifyDestinationPercentageOfScreen: 60
MainWindowState: Docked
KalmanFilterMeasurementNoise: 1000
PresageNumberOfSuggestions: 11
MainWindowDockSize: Full
LookToScrollOverlayBoundsThickness: 1
UseCommuniKateKeyboardLayoutByDefault:   False
SuggestNextWords: False
MainWindowDockPosition: Top
CommuniKateKeyboardPrevious4Context:
MouseMagnifierLockedDown: False
ToastNotificationHorizontalFillPercentage:   75
MultiKeySelectionMaxDuration: 00:01:00
MaryTTSVoice: cmu-slt-hsmm en_US female   hmm
InfoSoundFile: Resources\Sounds\Tone1.wav
NGramAutoCompleteGramCount: 3
MouseOnlyMode: False
MultiKeySelectionCaptureStartSoundFile:   Resources\Sounds\Rising1.wav
ShowSplashScreen: True
MultiKeySelectionFixationMinDwellTime:   00:00:00.2500000
MouseDragDelayAfterLeftMouseButtonDownBeforeMove:   00:00:00.0500000
ForceCapsLock: False
KalmanFilterEnabled: False
KeySelectionTriggerKeyboardKeyDownUpKey:   Control
MainWindowCollapsedDockThicknessAsPercentageOfFullDockThickness:   20
MainWindowPreviousState: Docked
CommuniKateKeyboardPrevious2Context:
CommuniKateSpeakSelected: False
LookToScrollEnabled: False
LookToScrollLockDownBoundsKey: False
FontWeight: Light
SuppressAutoCapitaliseIntelligently: True
PointSelectionTriggerFixationLockOnTime:   00:00:00.2500000
TETCalibrationCheckTimeSpan: 00:00:03
CommuniKateDefaultBoard:
MainWindowMinimisedPosition:   SameAsDockedPosition
PointsSource: TobiiPcEyeMini
SuggestionMethod: Presage
LookToScrollResumeAfterChoosingPointForMouse:   True
PointSelectionTriggerFixationCompleteTime:   00:00:01.2500000
LookToScrollAccelerationFast: 0.020
MouseClickSoundVolume: 0
PluginsLocation:   C:\Users\matth\AppData\Roaming\OptiKey\OptiKey\Plugins\
LookToScrollSuspendBeforeChoosingPointForMouse:   True
LookToScrollAccelerationSlow: 0.005
CommuniKateKeyboardPrevious3Context:
StartupKeyboardFile:
LookToScrollBringWindowToFrontAfterChoosingScreenPoint:   True
ConversationConfirmOnlyMode: False
PublishVirtualKeyCodesForCharacters: True
MoveAndResizeAdjustmentAmountInPixels: 25
CommuniKateSpeakSelectedVolume: 100
MultiKeySelectionEnabled: True
KalmanFilterInitialValue: 0
StartupKeyboard: Alpha
PointsMousePositionHideCursor: False
KalmanFilterConfidenceOfInitialValue: 0
KeySelectionTriggerSource:   KeyboardKeyDownsUps
KeySelectionTriggerFixationDefaultCompleteTime:   00:00:01.2500000
LookToScrollAccelerationMedium: 0.010
LookToScrollOverlayDeadzoneColour: Orange
NGramAutoCompleteTrailingSpaceCount: 1
MouseDownSoundFile:   Resources\Sounds\MouseDown1.wav
MouseUpSoundVolume: 0
LookToScrollDeactivateUponSwitchingKeyboards:   True
DisplayVoicesWhenChangingKeyboardLanguage:   True
CommuniKateSpeakSelectedRate: 0
LookToScrollShowOverlayWindow: True
MultiKeySelectionCaptureEndSoundVolume: 0
FontStretch: Condensed
ConversationConfirmEnable: False
TobiiEyeXProcessingLevel: Medium
LookToScrollCentreMouseWhenActivated:   True
LookToScrollIncrementChoices: 1, 2, 4,   10, 12, 30, 60, 120
MouseDragNumberOfSteps: 100
MouseDownSoundVolume: 1
KeySelectionTriggerMouseDownUpButton:   Left
UseSimplifiedKeyboardLayout: False
ErrorSoundFile:   Resources\Sounds\Tone2.wav
CommuniKateKeyboardCurrentContext:   toppage
SpeechVoice:
ToastNotificationMinimumTimeSeconds: 2
LookToScrollOverlayBoundsColour: Yellow
SuppressModifierKeysForAllMouseActions:   True
LookToScrollBounds: ScreenPoint
SpeechDelay: 0
KeySelectionTriggerFixationLockOnTime:   00:00:00.2500000
SettingsUpgradeRequired: False
EnableQuitKeys: True
MouseScrollAmountInClicks: 3
KeySelectionTriggerIncompleteFixationTtl:   00:00:00.7500000
MouseDoubleClickSoundVolume: 0
KeySelectionSoundFile:   Resources\Sounds\Click1.wav
TypeDiacriticsAfterLetters: False
KeyCase: Upper
MouseClickSoundFile:   Resources\Sounds\MouseClick1.wav
LookToScrollDirectionInverted: False
MultiKeySelectionCaptureEndSoundFile:   Resources\Sounds\Falling1.wav
GazeTrackerUdpPort: 6666
KeySelectionTriggerFixationCompleteTimesByKeyValues:   JuliusSweetland.OptiKey.Models.SerializableDictionaryOfTimeSpanByKeyValues
MagnifySuppressedForScrollingActions:   True
ScratchpadNumberOfLines: 2
CursorHeightInPixels: 90
ProgressIndicatorResizeEndProportion: 20
MainWindowFloatingSizeAndPosition:   256,144,1024,576
Debug: False
CommuniKateStagedForDeletion: False
ConversationBorderThickness: 1,1,1,1
LookToScrollSpeed: Medium
ToastNotificationSecondsPerCharacter:   0.02
CalibrationMaxDuration: 00:01:00
CursorWidthInPixels: 60
LookToScrollBaseSpeedMedium: 0
MouseScrollSoundVolume: 0
LookToScrollBringWindowToFrontWhenActivated:   True
AutoAddSpace: True
SuggestWords: True
AutoCloseCrashMessageSeconds: 10
LookToScrollMode: Free
KeyboardAndDictionaryLanguage: EnglishUK
ErrorSoundVolume: 0
AttentionSoundVolume: 0
MainWindowOpacity: 1
MouseUpSoundFile:   Resources\Sounds\MouseUp1.wav
MultiKeySelectionLockedDownWhenSimulatingKeyStrokes:   False
CommuniKatePagesetLocation:   ./Resources/CommuniKate/pageset.obz
MainWindowFullDockThicknessAsPercentageOfScreen:   50
SuppressModifierKeysWhenInMouseKeyboard:   True
UsingCommuniKateKeyboardLayout: False
CrashMessageFontSize: 25
CheckForUpdates: True
LookToScrollHorizontalDeadzone: 50
MaxDictionaryMatchesOrSuggestions: 20
EnableAttentionKey: False
MultiKeySelectionTriggerStopSignal:   NextLow
MouseDragDelayAfterMoveBeforeLeftMouseButtonUp:   00:00:00.0500000
ProgressIndicatorBehaviour: FillPie
MouseDoubleClickSoundFile:   Resources\Sounds\MouseDoubleClick1.wav
SelectionTriggerStopSignal: NextHigh
KeySelectionTriggerFixationCompleteTimesByIndividualKey:   True
MouseDragDelayBetweenEachStep:   00:00:00.0050000
InfoSoundVolume: 0
UiLanguageFlowDirection: LeftToRight
IrisbondCalibrationTargetCount: 9
LookToScrollVerticalDeadzone: 50
FontFamily: /Resources/Fonts/#Roboto
KeyboardLayout: Default
ConversationOnlyMode: False
IrisbondProcessingLevel: None
PointSelectionTriggerFixationRadiusInPixels:   60

[OptiKeyPro.log](https://github.com/OptiKey/OptiKey/files/4941366/OptiKeyPro.log)

**Comment by JuliusSweetland** [comment]
@AdamRoden This crash is related to the 'OverrideTimesByKey' property. The above combination of settings is resulting in this unimplemented property on KeyboardKeyDownUpSource. Do you know how to guard against this?

**Comment by AdamRoden** [comment]
@JuliusSweetland If you are offering to teach me something, my answer is "Tell me." Otherwise, if you are asking what I think, my first guess is that I used poor technique in the section of code highlighted here.

![image](https://user-images.githubusercontent.com/45572061/87853698-d83fc780-c8d1-11ea-9825-20f923b6c88f.png)

**Comment by JuliusSweetland** [comment]
@AdamRoden Sorry, I wasn't clear. I was asking really. That section of code looks like the culpit. I'll aim to find a bit of time later to test why the keySelectionTriggerSource of KeyboardKeyDownsUps is considered an IFixationTriggerSource as your code looks like it should prevent this.

**Comment by JuliusSweetland** [comment]
@AdamRoden Nothing wrong with your code. The user was using v3.0.4 which did not include this check. Some of my links to download Optikey from the www.optikey.org site were still pointing to the old version. I have fixed this now. 

Closing this.
