### ISSUE TITLE
Dynamic keyboard crash (regression)

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#789]
This crash occurs on `origin/master` but not with installed v3.1.1.0. 

The following keyboard includes a Shift key with a custom background, and a `BackOne` key. If you load the keyboard and press `BackOne` twice in a row, the second time Optikey crashes. 

It has something to do with the `BackgroundColor` and the automatic hold-down of the Shift key for auto-capitalisation (?).

The exception is shown below. 

keyboard: [crash_backone.zip](https://github.com/OptiKey/OptiKey/files/7892434/crash_backone.zip)

> System.InvalidOperationException
  HResult=0x80131509
  Message='Background' property does not point to a DependencyObject in path '(0).(1)'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Media.Animation.Storyboard.VerifyPathIsAnimatable(PropertyPath path)
   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   at System.Windows.Media.Animation.Storyboard.BeginCommon(DependencyObject containingObject, INameScope nameScope, HandoffBehavior handoffBehavior, Boolean isControllable, Int64 layer)
   at System.Windows.Media.Animation.Storyboard.Begin(FrameworkElement containingObject)
   at JuliusSweetland.OptiKey.UI.Behaviours.KeyBehaviours.<>c__DisplayClass1_0.<BeginAnimationOnKeySelectionEventChanged>b__0(Object sender, EventArgs args) in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\Behaviours\KeyBehaviours.cs:line 23
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at JuliusSweetland.OptiKey.UI.Controls.Key.<>c__DisplayClass2_0.<OnLoaded>b__11(EventPattern`1 pattern) in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\Controls\Key.cs:line 135
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass4.<GetHandler>b__1(Object sender, TEventArgs eventArgs)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.FireKeySelectionEvent(KeyValue kv) in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\ViewModels\MainViewModel.cs:line 313
   at JuliusSweetland.OptiKey.Pro.App.<>c__DisplayClass3_0.<App_OnStartup>b__0(KeyValue kv) in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Pro\App.xaml.cs:line 114
   at JuliusSweetland.OptiKey.Services.KeyboardOutputService.AutoPressShiftIfAppropriate() in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Core\Services\KeyboardOutputService.cs:line 776
   at JuliusSweetland.OptiKey.Services.KeyboardOutputService.ProcessFunctionKey(FunctionKeys functionKey) in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Core\Services\KeyboardOutputService.cs:line 207
   at JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.<HandleFunctionKeySelectionResult>d__65.MoveNext() in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\ViewModels\MainViewModel.ServiceEventHandlers.cs:line 2336
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at JuliusSweetland.OptiKey.Pro.App.<>c.<Main>b__1_0() in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Pro\App.xaml.cs:line 64
   at JuliusSweetland.OptiKey.Pro.App.Main() in C:\code\OptiKey\src\JuliusSweetland.OptiKey.Pro\App.xaml.cs:line 76

**Comment by kmcnaught** [comment]
I take it back - it's not a new regression, I just had auto-capitalisation turned off in my installed 3.1.1.0. The crash occurs in earlier versions - probably ever since `KeyGroup`s were added, but the auto-capitalisation is necessary to hit the crash.

**Comment by kmcnaught** [comment]
@AdamRoden would it be possible to check if this bug is still present in your WIP branch and include a fix at the next major update of keyboard functionality?

**Comment by AdamRoden** [comment]
Still crashes. Not yet fixed.

**Comment by AdamRoden** [comment]
@kmcnaught Man, that was a tricky little bug to squash, but after exhausting dozens of dead ends, I finally pinpointed the conflict that needed to be fixed and took care of it.
